# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rnEmailAuthFirebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Analytics'


  # Pods for rnEmailAuthFirebase

  target 'rnEmailAuthFirebase-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'rnEmailAuthFirebaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rnEmailAuthFirebase-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rnEmailAuthFirebase-tvOS

  target 'rnEmailAuthFirebase-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
